### ISSUE TITLE
KillBillClient::API::NotFound

### ISSUE THREAD

**Issue by lsantaniello** [killbill/killbill-paypal-demo#1]
I installed killbill using docker and started killbill-paypal-demo using ruby.

The demo ui show successfully but when I click on Pay button I receve an unhautorized error

`sinatra.error 	KillBillClient::API::NotFound`

Could you please help me to resolve the issue?

Thanks

**Comment by pierre** [comment]
This is likely a configuration issue (e.g. wrong `KB_URL`).

Let's move the discussion to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
